version: "3.9"
services:
  stefanini_cont:
    build: .
    env_file: ./.env
    ports:
      - "3001:3001"
    links:
      - mysql_cont
  mysql_cont:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=stefanini
      - MYSQL_USER=stefanini_user
      - MYSQL_PASSWORD=stefanini_456
      - MYSQL_ROOT_PASSWORD=stefanini_pass