version: "3.9"
services:
  stefanini_cont:
    build: .
    env_file: ./.docker.env
    ports:
      - "8080:8080"
    links:
      - mysql_cont
  mysql_cont:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=stefanini
      - MYSQL_ROOT_PASSWORD=stefanini_root_pass